#ifndef TEXMINATOR_VARIABLEDECLARATIONSTATEMENT_H
#define TEXMINATOR_VARIABLEDECLARATIONSTATEMENT_H

#include "Statement.h"

class VariableDeclarationStatement : public Statement {

};


#endif //TEXMINATOR_VARIABLEDECLARATIONSTATEMENT_H
